#!/opt/ruby/bin/ruby

DESC="god daemon"
NAME="god"
DAEMON="#{NAME}"
PIDFILE="/var/run/#{NAME}.pid"
LOGFILE="/var/log/#{NAME}.log"
SCRIPTNAME="/etc/init.d/#{NAME}"
START_FLAGS="-l #{LOGFILE} -P #{PIDFILE}"

ENV["PATH"] = "/opt/ruby/bin:/opt/rubygems/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
ENV["GEM_HOME"] = "/opt/rubygems"

def read_pid
  begin
    @pid = File.read(PIDFILE).to_i
    @pid = nil if @pid == 0
  rescue
    @pid = nil
  end
end

def kill(code)
  Process.kill(code, @pid)
  true
rescue
  false
end

def running?
  @pid && kill(0)
end

def dead?
  @pid && !kill(0)
end

def start
  if running?
    puts "already running (#{@pid})"
    exit
  end

  if dead?
    clean_pid
  end

  puts "starting #{NAME}"
  system("#{DAEMON} #{START_FLAGS}")
end

def stop
  if not running?
    puts "not running"
    exit
  end

  puts "stopping #{NAME}"
  system("#{DAEMON} quit")
end

def restart
	if running?
		stop
		read_pid
	end
	start
end

def force_reload
	if running?
	  restart
	end
end

def clean_pid
  File.delete(PIDFILE)
end

read_pid
case ARGV[0]
when 'start'
  start
when 'stop'
  stop
when 'restart'
  if not running?
    start
  else
    restart
  end
when 'force-reload'
  force_reload
when 'status'
  if running?
    puts "running (#{@pid})"
  elsif dead?
    puts "dead (#{@pid})"
    exit!(1)
  else
    puts "not running"
    exit!(3)
  end
else
  puts "Usage: #{SCRIPTNAME} start|stop|restart|force-reload|status"
end

exit
