#!/bin/bash
rm -rf /opt/git/$1.git
echo $1
rm -rf /opt/tmp
rm -rf /opt/web
service nginx stop
killall -u redis
killall -u badger
[ "$(cat /etc/issue | egrep '(CentOS)|(Red\ Hat)')" ] && service mysqld stop
[ "$(cat /etc/issue | egrep '(Ubuntu)|(Debian)')" ] && service mysql stop
service god stop
cd /etc/badger/core/scripts/
chmod +x remove_gems
./remove_gems
cd /

iptables -F
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -i eth1 -j ACCEPT
iptables -A INPUT -j ACCEPT -m state --state RELATED,ESTABLISHED
iptables -A INPUT -p icmp -m icmp --icmp-type any -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
iptables -A INPUT -j REJECT --reject-with icmp-host-prohibited

rm -rf /etc/badger
